update_fastlane

default_platform(:android)

platform :android do
 
  desc "Update version & release Android build on Firebase"
  lane :release_on_firebase do

    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/
    vn = /versionName\s+"\d.\d.(\d+)"/
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode+1).to_s
    s[vn, 1] = (versionCode+1).to_s

    updatedVersionCode = s[re, 1]
    updatedVersionName = s[/versionName\s+"(\d.\d.\d+)"/, 1]
    
    f = File.new(path, 'w')
    f.write(s)
    f.close 

    build_android_app(
      task: 'assemble',
      build_type: 'Release'
    )

    commit = last_git_commit
    
    firebase_app_distribution(
      firebase_cli_token: "1//0geU53tX2aWsBCgYIARAAGBASNwF-L9IrOUsSQeQwn7ekZNV-WpdTC39RWaePRiT21BRqglwhEtlSEQYeeO7QtToYX4e99IeegFo",
      app: "1:19544678223:android:a33d9b410e9a290db32f3a",
      groups: "internal, External",
      android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
      release_notes: commit[:message]
    )

    slack(
      message: "🎉🤖🍀 Flutter Android App released! 🤖🍀 Download here 👉 https://appdistribution.firebase.dev/i/b623e5310929ab70",
      slack_url: "https://hooks.slack.com/services/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",
      payload: {  
        "Build Date" => Time.new.to_s
      },
      default_payloads: [:last_git_commit], 
      attachment_properties: {      
        fields: [{
          title: "🎊 Version",
          value: updatedVersionName + " (" + updatedVersionCode + ")",
          short: false 
        }]
      }
    )
  end

end
