// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbz0cfK5hi-Hi4xVhVkmwAhaaqRgOdoHo',
    appId: '1:19544678223:android:a33d9b410e9a290db32f3a',
    messagingSenderId: '19544678223',
    projectId: 'flutter-hms',
    storageBucket: 'flutter-hms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbfczDEGfWjotYbOaCYeLxXxN_uCrwCxI',
    appId: '1:19544678223:ios:a7bb21cc95bb495ab32f3a',
    messagingSenderId: '19544678223',
    projectId: 'flutter-hms',
    storageBucket: 'flutter-hms.appspot.com',
    iosClientId:
        '19544678223-lisp1tlhj2es8id94te05r4ss4n7og2f.apps.googleusercontent.com',
    iosBundleId: 'live.100ms.flutter',
  );
}
