# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Appium CI

on:
  push:
    branches: [ appium ]
  pull_request:
    branches: [ appium ]

jobs:
  build:
    runs-on: macos-latest
#     defaults:
#       run:
#         working-directory: ./test/Flutter_100ms_appium
    strategy:
      matrix: 
        api-level: [29]
        target: [default]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 16
      uses: actions/setup-java@v3.2.0
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version: '11'
    
    - name: Install and Run Appium Server
      run: |
          npm install -g appium@v1.22.2
          appium -v
          appium &>/dev/null &
          ls
          
    - name: Android Emulator Runner
      uses: ReactiveCircus/android-emulator-runner@v2.23.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: avdmanager list device
#         force-avd-creation: false
#         emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -no-boot-anim none
        script: mvn test
        working-directory: ./test/Flutter_100ms_appium
#         script: mvn clean run -Pandroid

  
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml
