name: Build

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - develop
    paths-ignore:
      - "**.md"
      - doc/**
      - .git/
      - .vscode/

jobs:
  build_appbundle:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 12.x
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - name: Run Linters
        run: |
          dart format .;dart fix --apply
          git status
        shell: bash
      - name: Build Android
        run: |
          cd packages/hmssdk_flutter/example
          flutter build appbundle --debug -t lib/main.dart
        shell: bash
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🤖 automated changes by HMSBot
          repository: .
          commit_user_name: HMSBot
