name: 100ms-flutter

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8'
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Reading Secrets
      env :
        data: ${{secrets.GOOGLE_SERVICES_JSON}}
    - run: cd example
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release --no-codesign
    - run: flutter build ios --release --no-codesign
    
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: example/build/app/outputs/apk/release/app-release.apk
