name: Trunk Check
on:
  # trunk-ignore(yamllint/empty-values)
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - docs/**
      - .github/**

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  trunk_check:
    name: Run Trunk Check
    runs-on: ubuntu-latest
    permissions:
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          post-annotations: true
